export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_USERPROFILE: "SET_USERPROFILE",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
  SET_PLAYLIST: "SET_PLAYLIST",
};
