export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_USERPROFILE: "SET_USERPROFILE",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  SET_DEVICE_ID: "SET_DEVICE_ID",
  SET_SHUFFLE_STATE: "SET_SHUFFLE_STATE",
};
